### Adding item to market

POST http://localhost:3000/market/listing/create HTTP/1.1
Content-Type: application/json

{
    "itemName": "M4A1",
    "accountID": "76561198213884255",
    "listPrice": 500, 
    "condition": 2
}

### Edit listing

POST http://localhost:3000/market/edit HTTP/1.1
Content-Type: application/json

{
    "_id": "5fd33dca6e472e3140bdb28a",
    "listPrice": 500
}

### Register new user

POST http://localhost:3000/account/register HTTP/1.1
Content-Type: application/json

{
    "accountID": "76561198213884255"
}

### Get account listings
POST http://localhost:3000/account/listings HTTP/1.1
Content-Type: application/json

{
    "accountID": "76561198213884255",
    "limit": 5,
    "offset": 0,
    "searchFilter": ""
}

### Get account summary
POST http://localhost:3000/account/summary HTTP/1.1
Content-Type: application/json

{
    "accountID": "76561198213884255"
}


### Claim Balance
POST http://localhost:3000/account/balance/claim HTTP/1.1
Content-Type: application/json

{
    "accountID": "76561198213882024"
}


### Add new config item to Market Configs

POST http://localhost:3000/config/create HTTP/1.1
Content-Type: application/json

{
    "itemName": "AK74",
    "minPrice": 0,
    "maxPrice": 5000
}

### Retrieve listing configs

POST http://localhost:3000/config/listings HTTP/1.1
Content-Type: application/json

{
    "searchFilter": "",
    "limit": 0,
    "offset": 0
}

### Retrieve market listings

POST http://localhost:3000/market/listings HTTP/1.1
Content-Type: application/json

{
    "limit": 5,
    "offset": 0
}

### Retrieve market extremes(low/high)
GET http://localhost:3000/market/extremes HTTP/1.1
Content-Type: application/json

{

}

### Retrieve market index


POST https://dayz-marketplace-api.herokuapp.com/market/indeces HTTP/1.1
Content-Type: application/json

{
    "searchFilter" : "",
    "limit": 5,
    "offset": 0
}


### test

POST https://dayz-marketplace-api.herokuapp.com/ HTTP/1.1
Content-Type: application/json


### Buy Item
POST http://localhost:3000/market/buy HTTP/1.1
Content-Type: application/json

{
    "_id": "5fd3249734b438091805a595",
    "reclaim": true,
    "listPrice": 814
}

### Buy Item
POST http://localhost:3000/market/buycheapest HTTP/1.1
Content-Type: application/json

{
    "itemID": "5fd2abd38936ef32bcfff3ad",
    "condition": 1
}




