### Adding item to market

POST http://localhost:3000/market/listing/create HTTP/1.1
Content-Type: application/json

{
    "itemName": "AK",
    "accountID": "76561198213882024",
    "listPrice": 5000, 
    "condition": 1
}

### Register new user

POST http://localhost:3000/account/register HTTP/1.1
Content-Type: application/json

{
    "accountID": "76561198213882024"
}

### Get account listings
GET http://localhost:3000/account/listings HTTP/1.1
Content-Type: application/json

{
    "_id": "5fd2abfb8936ef32bcfff3ae",
    "limit": 50,
    "offset": 900
}

### Claim Balance
POST http://localhost:3000/account/balance/claim HTTP/1.1
Content-Type: application/json

{
    "accountID": "5fd2abfb8936ef32bcfff3ae"
}


### Add new config item to Market Configs

POST http://localhost:3000/config/create HTTP/1.1
Content-Type: application/json

{
    "itemName": "AK",
    "minPrice": 0,
    "maxPrice": 5000
}

### Retrieve listing configs

GET http://localhost:3000/config/listings HTTP/1.1
Content-Type: application/json

{
    "searchFilter": "UMP45",
    "limit": 0,
    "offset": 0
}

### Retrieve market listings

GET http://localhost:3000/market/listings HTTP/1.1
Content-Type: application/json

{
    "searchFilter": "ump",
    "limit": 0,
    "offset": 0
}

### Retrieve market extremes(low/high)
GET http://localhost:3000/market/extremes HTTP/1.1
Content-Type: application/json

{

}

### Retrieve market index


GET http://localhost:3000/market/indeces HTTP/1.1
Content-Type: application/json


### Buy Item
POST http://localhost:3000/market/buy HTTP/1.1
Content-Type: application/json

{
    "_id": "5fd29124a7ec2d2e848b507c"
}

### Buy Item
POST http://localhost:3000/market/buycheapest HTTP/1.1
Content-Type: application/json

{
    "itemID": "5fd2abd38936ef32bcfff3ad",
    "condition": 1
}


